---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: crap-cluster
  region: us-east-2
  version: "1.27"

nodeGroups:
  - name: ng-crap-cluster
    instanceType: t2.micro
    desiredCapacity: 3
    amiFamily: Bottlerocket
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    bottlerocket:
      settings:
        kernel:
          sysctl: 
            vm.max_map_count: "262144"
